### ISSUE TITLE
Auto Update Of Database

### ISSUE THREAD

**Issue by pengilton** [NikifFleser/FlaskWebTest#14]
Find a way to update the database after each match. In detail:

- [ ] update match result after each match
- [ ] evaluate the match specific bet afterwards
- [x] update scores in leaderboard

I already implemented a function to update the leaderboard. It gets called whenever a user clicks on the leaderboard. Technically, we only need to update the leaderboard after each match not whenever a user checks the leaderboard. I will create a separate issue for this.

Note that the tasks above are kinda tied together:
_match finishes -> insert result into db -> evaluate bets -> update leaderboard_

**Comment by NikifFleser** [comment]
We downgraded our expectations on this task. We do exactly what we didn't want - we should update the results in the database whenever the route gets called.
